metadata:
  name: olm
kind: Namespace
apiVersion: v1
---
metadata:
  name: operators
kind: Namespace
apiVersion: v1
---
metadata:
  name: olm-operator
  namespace: olm
kind: ServiceAccount
apiVersion: v1
---
metadata:
  name: system:controller:operator-lifecycle-manager
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
---
metadata:
  name: system:controller:operator-lifecycle-manager
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
subjects:
  - name: olm-operator
    namespace: olm
    kind: ServiceAccount
roleRef:
  name: system:controller:operator-lifecycle-manager
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
metadata:
  name: olm-operator
  labels:
    app: olm-operator
  namespace: olm
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: olm-operator
  nodeSelector:
    kubernetes.io/os: linux
  template:
    metadata:
      labels:
        app: olm-operator
    spec:
      serviceAccountName: olm-operator
      containers:
        - name: olm-operator
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: olm-operator
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
          image: quay.io/operator-framework/olm:latest
          command:
            - /bin/olm
          args:
            - --namespace
            - $(OPERATOR_NAMESPACE)
          ports:
            - name: health
              containerPort: 8080
            - name: metrics
              protocol: TCP
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          terminationMessagePolicy: FallbackToLogsOnError
          imagePullPolicy: IfNotPresent
  replicas: 1
kind: Deployment
apiVersion: apps/v1
---
metadata:
  name: catalog-operator
  labels:
    app: catalog-operator
  namespace: olm
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: catalog-operator
  nodeSelector:
    kubernetes.io/os: linux
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: olm-operator
      containers: []
  replicas: 1
kind: Deployment
apiVersion: apps/v1
---
metadata:
  name: aggregate-olm-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - catalogsources
      - installplans
      - subscriptions
    verbs:
      - delete
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
---
metadata:
  name: aggregate-olm-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - catalogsources
      - installplans
      - subscriptions
      - operatorgroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests
      - packagemanifests/icon
    verbs:
      - get
      - list
      - watch
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
---
metadata:
  name: global-operators
  namespace: operators
spec: {}
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
---
metadata:
  name: olm-operators
  namespace: olm
spec:
  targetNamespaces:
    - openshift-operator-lifecycle-manager
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
---
status: {}
metadata:
  name: packageserver
  labels:
    olm.version: 0.0.0
    olm.clusteroperator.name: operator-lifecycle-manager-packageserver
  namespace: olm
spec:
  displayName: Package Server
  description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
  version: 0.0.0
  install:
    spec:
      deployments:
        - name: packageserver
          spec:
            strategy:
              type: RollingUpdate
            selector:
              matchLabels:
                app: packageserver
            template:
              metadata:
                labels:
                  app: packageserver
              spec:
                serviceAccountName: olm-operator
                containers:
                  - name: packageserver
                    resources:
                      requests:
                        cpu: 10m
                        memory: 160Mi
                    image: quay.io/operator-framework/olm:latest
                    command:
                      - /bin/package-server
                    args:
                      - --secure-port
                      - "5443"
                      - --global-namespace
                      - olm
                    ports:
                      - name: server
                        containerPort: 5443
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 5443
                    readinessProbe:
                      httpGet:
                        path: /healthz
                        port: 5443
                    terminationMessagePolicy: FallbackToLogsOnError
                    imagePullPolicy: IfNotPresent
                nodeSelector:
                  kubernetes.io/os: linux
            replicas: 2
      clusterPermissions:
        - rules:
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
                - get
            - apiGroups:
                - '""'
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - operators.coreos.com
              resources:
                - catalogsources
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - packages.operators.coreos.com
              resources:
                - packagemanifests
              verbs:
                - get
                - list
          serviceAccountName: olm-operator-serviceaccount
    strategy: deployment
  maturity: alpha
  apiservicedefinitions:
    owned:
      - name: packagemanifests
        displayName: PackageManifest
        description: A PackageManifest is a resource generated from existing CatalogSources which represents operators avaialable for install.
        version: v1
        kind: PackageManifest
        group: packages.operators.coreos.com
        deploymentName: packageserver
        containerPort: 5443
  minKubeVersion: 1.11.0
  keywords:
    - packagemanifests
    - olm
    - packages
  maintainers:
    - name: Red Hat
      email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  links:
    - name: Package Server
      url: https://github.com/operator-framework/operator-lifecycle-manager
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
---
status: {}
metadata:
  name: operatorhubio-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/operator-framework/upstream-community-operators:latest
  displayName: Community Operators
  publisher: OperatorHub.io
kind: CatalogSource
apiVersion: operators.coreos.com/v1alpha1
