metadata:
  name: olm-operator
  namespace: openshift-operator-lifecycle-manager
kind: ServiceAccount
apiVersion: v1
---
metadata:
  name: system:controller:operator-lifecycle-manager
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
---
metadata:
  name: system:controller:operator-lifecycle-manager
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
subjects:
  - name: olm-operator
    namespace: openshift-operator-lifecycle-manager
    kind: ServiceAccount
roleRef:
  name: system:controller:operator-lifecycle-manager
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
