status: {}
metadata:
  name: packageserver
  labels:
    olm.version: 0.0.0
    olm.clusteroperator.name: operator-lifecycle-manager-packageserver
  namespace: openshift-operator-lifecycle-manager
spec:
  displayName: Package Server
  description: Represents an Operator package that is available from a given CatalogSource which will resolve to a ClusterServiceVersion.
  version: 0.0.0
  install:
    spec:
      deployments:
        - name: packageserver
          spec:
            strategy:
              type: RollingUpdate
            selector:
              matchLabels:
                app: packageserver
            template:
              metadata:
                labels:
                  app: packageserver
              spec:
                serviceAccountName: olm-operator
                containers:
                  - name: packageserver
                    resources:
                      requests:
                        cpu: 10m
                        memory: 160Mi
                    image: quay.io/operator-framework/olm:latest
                    command:
                      - /bin/package-server
                    args:
                      - --secure-port
                      - "5443"
                      - --global-namespace
                      - openshift-marketplace
                    ports:
                      - name: server
                        containerPort: 5443
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 5443
                    readinessProbe:
                      httpGet:
                        path: /healthz
                        port: 5443
                    terminationMessagePolicy: FallbackToLogsOnError
                    imagePullPolicy: IfNotPresent
                nodeSelector:
                  kubernetes.io/os: linux
                  node-role.kubernetes.io/master: ""
                tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: NoSchedule
                  - key: node.kubernetes.io/unreachable
                    operator: Exists
                    effect: NoExecute
                    tolerationSeconds: 120
                  - key: node.kubernetes.io/not-ready
                    operator: Exists
                    effect: NoExecute
                    tolerationSeconds: 120
            replicas: 2
      clusterPermissions:
        - rules:
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
                - get
            - apiGroups:
                - '""'
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - operators.coreos.com
              resources:
                - catalogsources
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - packages.operators.coreos.com
              resources:
                - packagemanifests
              verbs:
                - get
                - list
          serviceAccountName: olm-operator-serviceaccount
    strategy: deployment
  maturity: alpha
  apiservicedefinitions:
    owned:
      - name: packagemanifests
        displayName: PackageManifest
        description: A PackageManifest is a resource generated from existing CatalogSources which represents operators avaialable for install.
        version: v1
        kind: PackageManifest
        group: packages.operators.coreos.com
        deploymentName: packageserver
        containerPort: 5443
  minKubeVersion: 1.11.0
  keywords:
    - packagemanifests
    - olm
    - packages
  maintainers:
    - name: Red Hat
      email: openshift-operators@redhat.com
  provider:
    name: Red Hat
  links:
    - name: Package Server
      url: https://github.com/operator-framework/operator-lifecycle-manager
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
